 URL : "https://github.com/VUnit/vunit/issues/231" TITLE : add questa support BODY : i tried to get questa 10.5 running and tried both the 32 bit and the 64 bit version. as it turns out mentor changed the encoding of modelsim.ini to utf-8 and that yields following error when using it with vunit: > traceback most recent call last : > file c:\tools\python35-32\lib\site-packages\vunit_hdl-0.71.0-py3.5.egg\vunit\ui.py , line 689, in main > all_ok = self._main > file c:\tools\python35-32\lib\site-packages\vunit_hdl-0.71.0-py3.5.egg\vunit\ui.py , line 723, in _main > self._compile simulator_if > file c:\tools\python35-32\lib\site-packages\vunit_hdl-0.71.0-py3.5.egg\vunit\ui.py , line 827, in _compile > continue_on_error=self._keep_compiling > file c:\tools\python35-32\lib\site-packages\vunit_hdl-0.71.0-py3.5.egg\vunit\simulator_interface.py , line 119, in compile_project > self.setup_library_mapping project > file c:\tools\python35-32\lib\site-packages\vunit_hdl-0.71.0-py3.5.egg\vunit\modelsim_interface.py , line 168, in setup_library_mapping > mapped_libraries = self._get_mapped_libraries > file c:\tools\python35-32\lib\site-packages\vunit_hdl-0.71.0-py3.5.egg\vunit\modelsim_interface.py , line 248, in _get_mapped_libraries > cfg.read self._modelsim_ini > file c:\tools\python35-32\lib\configparser.py , line 696, in read > self._read fp, filename > file c:\tools\python35-32\lib\configparser.py , line 1012, in _read > for lineno, line in enumerate fp, start=1 : > file c:\tools\python35-32\lib\encodings\cp1252.py , line 23, in decode > return codecs.charmap_decode input,self.errors,decoding_table 0 > unicodedecodeerror: 'charmap' codec can't decode byte 0x9d in position 3239: character maps to <undefined> for now i just converted questas modelsim.ini from utf to 8859 and it works fine. but of course it would be nice if vunit would resolve those encoding issues.