 URL : "https://github.com/psy0rz/zfs_autobackup/issues/1" TITLE : tab & space mixing BODY : lines 446-452 have mixed tabs & spaces causing python error on execution. $/tmp/zfs_autobackup/zfs_autobackup file /tmp/zfs_autobackup/zfs_autobackup , line 447 error= cant find latest target snapshot on source, did you destroy it accidently? +source_filesystem+ @ +latest_target_snapshot ^ taberror: inconsistent use of tabs and spaces in indentation