 URL : "https://github.com/simonvh/gimmemotifs/issues/58" TITLE : gimme cluster error BODY : traceback most recent call last : file /home/simon/anaconda2/envs/gimme/bin/gimme , line 496, in <module> args.func args file /home/simon/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/cluster.py , line 84, in cluster ids = _create_images outdir, clusters file /home/simon/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/cluster.py , line 53, in _create_images add_pos = sorted scores.values ,cmp=lambda x,y: cmp x 1 , y 1 0 1 typeerror: 'cmp' is an invalid keyword argument for this function