 URL : "https://github.com/Miserlou/Zappa/issues/588" TITLE : z_cli.certify error BODY : when redeploying a site with recertify set, i see these errors in the cloudwatch logs: this application  31misn't deployed yet 0m - did you mean to call  1mdeploy 0m?: clickexception traceback most recent call last : file /var/task/handler.py , line 479, in lambda_handler return lambdahandler.lambda_handler event, context file /var/task/handler.py , line 192, in lambda_handler return handler.handler event, context file /var/task/handler.py , line 301, in handler return self.run_function app_function, event, context file /var/task/handler.py , line 237, in run_function result = app_function event, context file /var/task/handler.py , line 493, in certify_callback return lh.update_certificate file /var/task/handler.py , line 253, in update_certificate z_cli.certify file /private/var/folders/26/dklxrj8130l1rxw1r5qnb7nw0000gn/t/pip-build-4cs1fj/zappa/zappa/cli.py , line 1206, in certify clickexception: this application  31misn't deployed yet 0m - did you mean to call  1mdeploy 0m?