 URL : "https://github.com/erickrf/nlpnet/issues/35" TITLE : invalid data directory BODY : i am trying to run your repository and getting the following issue: traceback most recent call last : file <stdin> , line 1, in <module> file /usr/local/lib/python2.7/dist-packages/nlpnet/taggers.py , line 307, in __init__ super dependencyparser, self .__init__ args, kwargs file /usr/local/lib/python2.7/dist-packages/nlpnet/taggers.py , line 190, in __init__ self.paths = config.get_config_paths data_dir file /usr/local/lib/python2.7/dist-packages/nlpnet/config.py , line 14, in get_config_paths assert os.path.isdir directory , 'invalid data directory' assertionerror: invalid data directory please help me soon. i am in a bit urgency.