 URL : "https://github.com/smicallef/spiderfoot/issues/141" TITLE : traceback w/ builtwith BODY : latest github pull: v2.11 running a scan produces this after 6 items are retrieved. unhandled exception typeerror encountered during scan. please report this as a bug: 'traceback most recent call last : ', ' file /opt/spiderfoot/sfscan.py , line 265, in startscan psmod.notifylisteners firstevent ', ' file /opt/spiderfoot/sflib.py , line 1523, in notifylisteners listener.handleevent sfevent ', ' file /opt/spiderfoot/modules/sfp_bingsearch.py , line 93, in handleevent self.notifylisteners evt ', ' file /opt/spiderfoot/sflib.py , line 1523, in notifylisteners listener.handleevent sfevent ', ' file /opt/spiderfoot/modules/sfp_dnsresolve.py , line 150, in handleevent self.processhost match 1 , parentevent, false ', ' file /opt/spiderfoot/modules/sfp_dnsresolve.py , line 322, in processhost self.notifylisteners evt ', ' file /opt/spiderfoot/sflib.py , line 1523, in notifylisteners listener.handleevent sfevent ', ' file /opt/spiderfoot/modules/sfp_bingsearch.py , line 93, in handleevent self.notifylisteners evt ', ' file /opt/spiderfoot/sflib.py , line 1523, in notifylisteners listener.handleevent sfevent ', ' file /opt/spiderfoot/modules/sfp_dnsresolve.py , line 150, in handleevent self.processhost match 1 , parentevent, false ', ' file /opt/spiderfoot/modules/sfp_dnsresolve.py , line 326, in processhost self.processdomain dom, evt ', ' file /opt/spiderfoot/modules/sfp_dnsresolve.py , line 345, in processdomain self.notifylisteners domevt ', ' file /opt/spiderfoot/sflib.py , line 1523, in notifylisteners listener.handleevent sfevent ', ' file /opt/spiderfoot/modules/sfp_builtwith.py , line 97, in handleevent for nb in data \'meta\' \'names\' : ', typeerror: 'nonetype' object is not iterable