 URL : "https://github.com/28kayak/todo_app/issues/2" TITLE : could not connect to db BODY : connection error: { mongoerror: auth failed at object.toerror c:\users\kaya\documents\todo_app ode_modules\mongodb\lib\mongodb\utils.js:110:11 at c:\users\kaya\documents\todo_app ode_modules\mongodb\lib\mongodb\auth\mongodb_cr.js:34:33 at c:\users\kaya\documents\todo_app ode_modules\mongodb\lib\mongodb\db.js:1670:9 at server.base._callhandler c:\users\kaya\documents\todo_app ode_modules\mongodb\lib\mongodb\connection\base.js:382:41 at c:\users\kaya\documents\todo_app ode_modules\mongodb\lib\mongodb\connection\server.js:472:18 at mongoreply.parsebody c:\users\kaya\documents\todo_app ode_modules\mongodb\lib\mongodb\responses\mongo_reply.js:68:5 at .<anonymous> c:\users\kaya\documents\todo_app ode_modules\mongodb\lib\mongodb\connection\server.js:430:20 at emitone events.js:96:13 at emit events.js:188:7 at .<anonymous> c:\users\kaya\documents\todo_app ode_modules\mongodb\lib\mongodb\connection\connection_pool.js:191:13 name: 'mongoerror' , ok: 0, errmsg: 'auth failed', code: 18 }