 URL : "https://github.com/Feneric/doxypypy/issues/40" TITLE : exception on windows 10 BODY : i am running doxypypy on windows 10 and ran into the following exception. this seems to happen between reading and parsing a file which doesnt contain any docstrings or doxygen comments. i can't really share anything more as i work on a confidential project. i've gone through the files listed in the stacktrace below but can't seem to figure out why this would be the case. traceback most recent call last : file c:\python27\lib\runpy.py , line 174, in _run_module_as_main __main__ , fname, loader, pkg_name file c:\python27\lib\runpy.py , line 72, in _run_code exec code in run_globals file c:\python27\scripts\doxypypy.exe\__main__.py , line 9, in <module> file c:\python27\lib\site-packages\doxypypy\doxypypy.py , line 830, in main astwalker.parselines file c:\python27\lib\site-packages\doxypypy\doxypypy.py , line 743, in parselines self.visit inast file c:\python27\lib\site-packages\doxypypy\doxypypy.py , line 569, in visit return visitor node, containingnodes=containingnodes file c:\python27\lib\site-packages\doxypypy\doxypypy.py , line 595, in visit_module file c:\python27\lib\site-packages\doxypypy\doxypypy.py , line 553, in generic_visit self.visit item, containingnodes=kwargs 'containingnodes' file c:\python27\lib\site-packages\doxypypy\doxypypy.py , line 569, in visit return visitor node, containingnodes=containingnodes file c:\python27\lib\site-packages\doxypypy\doxypypy.py , line 610, in visit_assign match = astwalker.__attributere.match self.lines linenum indexerror: list index out of range