 URL : "https://github.com/suriyadeepan/easy_seq2seq/issues/35" TITLE : typeerror in execute.py BODY : preparing data in working_dir/ creating 3 layers of 256 units. traceback most recent call last : file execute.py , line 300, in <module> train file execute.py , line 123, in train model = create_model sess, false file execute.py , line 95, in create_model model = seq2seq_model.seq2seqmodel gconfig 'enc_vocab_size' , gconfig 'dec_vocab_size' , _buckets, gconfig 'layer_size' , gconfig 'num_layers' , gconfig 'max_gradient_norm' , gconfig 'batch_size' , gconfig 'learning_rate' , gconfig 'learning_rate_decay_factor' , forward_only=forward_only file /home/localhost/test_case_1/seq2seq_model.py , line 167, in __init__ self.saver = tf.train.saver tf.initialize_all_variables file /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py , line 986, in __init__ self.build file /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py , line 1015, in build restore_sequentially=self._restore_sequentially file /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py , line 602, in build saveables = self._validateandsliceinputs names_to_saveables file /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py , line 498, in _validateandsliceinputs names_to_saveables = basesaverbuilder.oplisttodict names_to_saveables file /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py , line 453, in oplisttodict list: %s % op_list typeerror: variables to save should be passed in a dict or a list: name: init op: noop input: ^init/noop input: ^init/noop_1