 URL : "https://github.com/ContinuumIO/anaconda-issues/issues/3103" TITLE : application launch error BODY : main error application <b>spyder</b> launch may have produced errors. traceback warn kq_init: detected broken kqueue; not using.: undefined error: 0 warn kq_init: detected broken kqueue; not using.: undefined error: 0 warn kq_init: detected broken kqueue; not using.: undefined error: 0 warn kq_init: detected broken kqueue; not using.: undefined error: 0 warn kq_init: detected broken kqueue; not using.: undefined error: 0 warn kq_init: detected broken kqueue; not using.: undefined error: 0 warn kq_init: detected broken kqueue; not using.: undefined error: 0 system information python: 3.6.0 language: en os: darwin;16.6.0;darwin kernel version 16.6.0: fri apr 14 16:21:16 pdt 2017; root:xnu-3789.60.24~6/release_x86_64;x86_64;i386 version: 1.6.2 platform: osx-64 qt: 5.6.2 pyqt: 5.6.0 conda: 4.3.21