 URL : "https://github.com/ParrotPrediction/docker-course-xgboost/issues/5" TITLE : unable to import xg boost BODY : im unable to import xg boost in the python notebook import xgboost error in notebook: --------------------------------------------------------------------------- oserror traceback most recent call last <ipython-input-1-afdaff4619ce> in <module> ----> 1 import xgboost ~\anaconda3\lib\site-packages\xgboost-0.6-py3.6.egg\xgboost\__init__.py in <module> 9 import os 10 ---> 11 from .core import dmatrix, booster 12 from .training import train, cv 13 from . import rabit noqa ~\anaconda3\lib\site-packages\xgboost-0.6-py3.6.egg\xgboost\core.py in <module> 113 114 load the xgboost library globally --> 115 _lib = _load_lib 116 117 ~\anaconda3\lib\site-packages\xgboost-0.6-py3.6.egg\xgboost\core.py in _load_lib 107 if len lib_path == 0: 108 return none --> 109 lib = ctypes.cdll.loadlibrary lib_path 0 110 lib.xgbgetlasterror.restype = ctypes.c_char_p 111 return lib ~\anaconda3\lib\ctypes\__init__.py in loadlibrary self, name 424 425 def loadlibrary self, name : --> 426 return self._dlltype name 427 428 cdll = libraryloader cdll ~\anaconda3\lib\ctypes\__init__.py in __init__ self, name, mode, handle, use_errno, use_last_error 346 347 if handle is none: --> 348 self._handle = _dlopen self._name, mode 349 else: 350 self._handle = handle oserror: winerror 126 the specified module could not be found ! capture https://user-images.githubusercontent.com/25509837/33111356-9edb8040-cf1b-11e7-87f9-5eb6d735d74e.png