 URL : "https://github.com/aurotripathy/lstm-anomaly-detect/issues/2" TITLE : unable to run the program BODY : hi , i tried running this program but got following error : using tensorflow backend. loading data... 'wave1', 1000 'wave2', 1000 'wave3', 50 traceback most recent call last : file lstm-synthetic-wave-anomaly-detect.py , line 196, in <module> run_network file lstm-synthetic-wave-anomaly-detect.py , line 152, in run_network x_train, y_train, x_test, y_test = get_split_prep_data 0, 700, 500, 1000 file lstm-synthetic-wave-anomaly-detect.py , line 70, in get_split_prep_data data = gen_wave file lstm-synthetic-wave-anomaly-detect.py , line 56, in gen_wave wave1 insert:insert + 50 = wave1 insert:insert + 50 + wave3 typeerror: slice indices must be integers or none or have an __index__ method i did not modify anything , just ran the code as it is yet got this error . can you please help what went wrong ?